### ISSUE TITLE
No array type.

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#248]
There's no way to define the following struct with DEFCSTRUCT:

   struct foo {
      unsigned int bar[12];
      unsigned char baz[6];
    };

The problem is that you can't define fixed-size arrays as a type in CFFI. There's just no way to do it. I don't think it can be done with DEFINE-FOREIGN-TYPE. :pointer would not work here.

Launchpad Details: [#LP1458413](https://bugs.launchpad.net/bugs/1458413) No  Name - 2015-05-25 00:00:35 +0000

**Comment by rssoc** [comment]
FOREIGN-ARRAY-TYPE exists but it's undocumented (as of writing).
```common-lisp
(defcstruct foo
  (bar (:array :uint 12))
  (baz (:array :uchar 6)))
```

**Comment by luismbo** [comment]
The original way to define such a struct is using the `:count` option. See the last example in https://cffi.common-lisp.dev/manual/html_node/defcstruct.html. But using the undocumented `:array` type is definitely nicer. Does it work? 🤔

**Comment by rssoc** [comment]
> Does it work?

See #362 :-)
