### ISSUE TITLE
Functions returning structs are not thread-safe

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#258]
When DEFCFUN is used to declare a function that returns a struct, the resulting function calls CFFI:FOREIGN-FUNCALL which expands into a call to CFFI:PREPARE-FUNCTION. This function is not thread-safe since it can alter the content of *CIF-TABLE*.

Note that this code-path is only followed for functions that are called through libffi (i.e. functions that returns structs). Plain functions are not affected by this.

PREPARE-FUNCTION should use a mutex or other mechanism to prevent parallel access to *CIF-TABLE*.

Another potential solution would be to run DEFCFUN during compile-time, although I don't know the implications of this.

Launchpad Details: [#LP1474211](https://bugs.launchpad.net/bugs/1474211) Elias Martenson - 2015-07-14 05:10:56 +0000

**Comment by sionescu** [comment]
Liam's fix at https://github.com/cffi/cffi/commit/bb5577baffae0137ae4087ee95cbd2df31b7ca87 (and discussion on IRC) suggests this is only an issue during compilation, but this bug report suggests otherwise. Which is which?

Launchpad Details: [#LPC](https://bugs.launchpad.net/cffi/+bug/1474211/comments/1) Luís Oliveira - 2016-01-08 11:34:53 +0000

**Comment by attila-lendvai** [comment]
this is obsolete, the value is only cached per function now.

arguably, it should use a CAS, but... closing.
