### ISSUE TITLE
Misleading comment in asdf.lisp

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#268]
The following comment seem to be wrong:

;; Allow for naked :grovel-file and :wrapper-file in asdf definitions.
(setf (find-class 'asdf::cffi-grovel-file) (find-class 'grovel-file))

Indeed, after that, :cffi-grovel-file and :wrapper-file should be recognized as component name,
not :grovel-file and :wrapper-file. 

This wrong comment is essential as there are two references from asdf manual to the code.

So the code should be considered as a "canonical example" of extending asdf. 

Figuring out what is wrong required an essential effort from me.

Launchpad Details: [#LP1532458](https://bugs.launchpad.net/bugs/1532458) Denis Budyak - 2016-01-09 16:18:14 +0000

**Comment by attila-lendvai** [comment]
this has been fixed since then.
