### ISSUE TITLE
Error loading system definition on Clozure/CLISP/older SBCL

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#281]
Hi,

On Clozure (1.11.5), CLISP (2.49), and older versions of SBCL (e.g. 1.1.8) I get the following error when trying to load the system definition for CFFI:

Clozure:

? (ql:quickload :cffi)
> Error: Error while trying to load definition for system cffi from pathname /Users/elliott/quicklisp/dists/quicklisp/software/cffi_0.19.0/cffi.asd: (OPERATE 'TEST-OP :CFFI-TESTS) can't be destructured against the lambda list (O C), because it contains 3 elements, and exactly 2 are expected.
> While executing: (:INTERNAL LOAD-SYSDEF), in process Initial(0).

CLISP:

[1]> (ql:quickload :cffi)

*** - Error while trying to load definition for system cffi from pathname
      /Users/elliott/quicklisp/dists/quicklisp/software/cffi_0.19.0/cffi.asd: DESTRUCTURING-BIND: (OPERATE 'TEST-OP :CFFI-TESTS) does not
      match lambda list element (O C)

The error goes away when I comment out the following two lines in cffi.asd:

  ;; :in-order-to ((test-op (load-op :cffi-tests)))
  ;; :perform (test-op (o c) (operate 'asdf:test-op :cffi-tests))

This is CFFI version 0.19.0 from the latest Quicklisp.

If this is not a CFFI bug and should be reported elsewhere (e.g. to ASDF), apologies, please let me know and I will file it elsewhere.

Launchpad Details: [#LP1758766](https://bugs.launchpad.net/bugs/1758766) slaguth - 2018-03-25 23:52:08 +0000

**Comment by attila-lendvai** [comment]
cffi won't work when using ancient ASDF.

closing it.
