### ISSUE TITLE
Latest release is over a year old

### ISSUE THREAD

**Issue by lukego** [cffi/cffi#325]
I hope this does not come off as rude but I just wanted to point out that the latest cffi release is over a year old now.

One consequence of this is that the version carried by Quicklisp is not compatible with `libffi.so.8` which has been in circulation for a long time now. This would be fixed in a new release that carries #192.

(I mention this because I'm working around the libffi.so.8 issue in downstream packaging and suspect that others are doing such things too.)

**Comment by Gavinok** [comment]
Can confirm you are not the only one forced to use this workaround

**Comment by stylewarning** [comment]
I also just submitted a patch to include `libffi.so` as an additional fallback because of this.

**Comment by mdmintz** [comment]
https://pypi.org/project/cffi/1.15.1/ is available.

**Comment by yurivict** [comment]
Why aren't there new releases?

**Comment by notmgsk** [comment]
ping

**Comment by luismbo** [comment]
We've sort of fixed this by pointing Quicklisp to the master branch. A new release would be nice, in any case, but this should fix the Quicklisp issue.
