### ISSUE TITLE
Would it be possible to release wheels for manylinux10?

### ISSUE THREAD

**Issue by mariocj89** [cffi/cffi#329]
The latest release of cffi (1.15.1) does not ship 2010 many linux wheel for x86_64 whilst it used to do in 1.15.0.  Whilst I understand 2014 should support most if not all of the supported distributions, some users might still be in legacy platforms like RHEL6 (moving away, I promise :P).

Would it be possible to release 2010 wheels like it was for the previous version or are those "officially" unsupported from cffi perspective?

**Comment by luismbo** [comment]
wrong project
