### ISSUE TITLE
Please do not list shared library names with version names

### ISSUE THREAD

**Issue by yurivict** [cffi/cffi#331]
For example [here](https://github.com/cffi/cffi/blob/master/libffi/libffi.lisp#L34) libffi.so is listed with a variety of versions. For me some older version of that file is used which doesn't list ```libffi.so.8```.

What is the point of chasing individual version numbers vs. just listing ```libffi.so```?

**Comment by luismbo** [comment]
There are two reasons:

1. It makes sense to validate whether new versions which potentially break binary compatibility are in fact compatible.
2. Linux distributions often don't have a `libffi.so` file we can load, only versioned files.

In practice, the second reason is what's driving these long lists.
