### ISSUE TITLE
Update documentation for with-foreign-pointer-as-string

### ISSUE THREAD

**Issue by sdilts** [cffi/cffi#335]
`with-foreign-pointer-as-string` has incorrect documentation in the manual. In order to place the length of the buffer into a variable, it suggest the following syntax:

``` lisp
(with-foreign-pointer-as-string (str 6 str-size :encoding :ascii)
     (lisp-string-to-foreign "Hello, foreign world!" str str-size)))
```

However, it should actually look like this:

``` lisp
(with-foreign-pointer-as-string ((str str-size) 6 :encoding :ascii)
     (lisp-string-to-foreign "Hello, foreign world!" str str-size)))
```
The syntax needs to be corrected too.

Here's the current macro definition for reference: https://github.com/cffi/cffi/blob/e0b2f359666465bcd49432b9e596b38b9089c9a7/src/strings.lisp#L228

**Comment by b3ast-t** [comment]
The manual page hasn't been updated https://cffi.common-lisp.dev/manual/html_node/with_002dforeign_002dpointer_002das_002dstring.html
