### ISSUE TITLE
cffi does not work correctly on major BSDs.

### ISSUE THREAD

**Issue by tapioco71** [cffi/cffi#341]
/libffi/libffi.lisp should be:

(define-foreign-library (libffi)
  (:darwin (:or "libffi.dylib" "libffi32.dylib" "/usr/lib/libffi.dylib"))
  (:solaris (:or "/usr/lib/amd64/libffi.so" "/usr/lib/libffi.so"))
  ((or :freebsd :openbsd :netbsd) "libffi.so")
  (:unix (:or "libffi.so.7" "libffi32.so.7" "libffi.so.6" "libffi32.so.6" "libffi.so.5" "libffi32.so.5"))
  (:windows (:or "libffi-7.dll" "libffi-6.dll" "libffi-5.dll" "libffi.dll"))
  (t (:default "libffi")))

**Comment by phoe** [comment]
So, IIUC, the fix is to add `:NETBSD` in a proper place, namely, turn `((or :freebsd :openbsd) "libffi.so")` into `((or :freebsd :openbsd :netbsd) "libffi.so")`. Can I ask for a PR that does this?
