### ISSUE TITLE
LOADing cffi interns SPLIT-STRING in CL-USER

### ISSUE THREAD

**Issue by ILoveGoulash** [cffi/cffi#352]
Hello
```
CL-USER> (find-symbol "SPLIT-STRING")
NIL
NIL
CL-USER> (ql:quickload :cffi)
To load "cffi":
  Load 1 ASDF system:
    cffi
; Loading "cffi"
............
(:CFFI)
CL-USER> (find-symbol "SPLIT-STRING")
SPLIT-STRING
:INTERNAL
```
Nothing horrible, just produces some conflicts when `use`ing uiop or other utility libraries. Don't really know where it comes from, though.

**Comment by phoe** [comment]
What is your implementation?

https://github.com/cffi/cffi/blob/33970351e71bb5f12ba56fc40270089e948ae112/cffi.asd#L39

Maybe the actual issue is in one of the dependencies?

**Comment by phoe** [comment]
```lisp
* (ql:quickload :uiop)
To load "uiop":
  Load 1 ASDF system:
    uiop
; Loading "uiop"
(:UIOP)

* (find-symbol "SPLIT-STRING")
SPLIT-STRING
:INTERNAL
```

Sounds like https://gitlab.common-lisp.net/asdf/asdf might want to hear about this then.

**Comment by ILoveGoulash** [comment]
Oh I see. (was SBCL btw)
