### ISSUE TITLE
couldn't install cffi with setuptools > 65.1.1

### ISSUE THREAD

**Issue by perryitay** [cffi/cffi#353]
when I install setuptools > 65.1.1, and then try to install cffi : 
./python3.9 -s -m pip install cffi --no-binary :all: (I need to use the tar file in order to be able to use it for all os)

I get : 

    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/opt/redislabs/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-cpython-39/c/_cffi_backend.o
    c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1

**Comment by phoe** [comment]
https://foss.heptapod.net/pypy/cffi/

**Comment by perryitay** [comment]
sorry I don't understand. you don't plan to support newer versions of setuptools ?

**Comment by phoe** [comment]
You probably want to make an issue on the bugtracker of the Python CFFI project, not the bugtracker of the Common Lisp CFFI project.
