### ISSUE TITLE
The version (in quicklisp) cffi-20230214-git fails on C compile of iolib

### ISSUE THREAD

**Issue by wglb** [cffi/cffi#358]
CFFI-GROVEL fails with latest quick lisp version with the following slime report:

Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10034569C3}>
 with command ("cc" "-o"
               "/usr/home/wgl/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wgl/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel-tmpZ7CBRM0G.o"
               "-c" "-g" "-Wall" "-Wundef" "-Wsign-compare"
               "-Wpointer-arith" "-O3" "-fno-omit-frame-pointer"
               "-fPIC"
               "-I/usr/home/wgl/quicklisp/dists/quicklisp/software/cffi-20230214-git/"
               "/usr/home/wgl/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wgl/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel.c")
 exited with error code 1
   [Condition of type CFFI-GROVEL:GROVEL-ERROR]

Restarts:
 0: [RETRY] Retry #<PROCESS-OP > on #<GROVEL-FILE "iolib/syscalls" "ffi-types">.
 1: [ACCEPT] Continue, treating #<PROCESS-OP > on #<GROVEL-FILE "iolib/syscalls" "ffi-types"> as having been successful.
 2: [RETRY] Retry ASDF operation.
 3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 4: [RETRY] Retry ASDF operation.
 5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 6: [ABORT] Abort compilation.
 7: [*ABORT] Return to SLIME's top level.
 8: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10018D0003}>)

Backtrace:
  0: (CFFI-GROVEL:GROVEL-ERROR "~a" #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1003646DE3}>)
  1: ((FLET "THUNK" :IN CFFI-GROVEL:PROCESS-GROVEL-FILE))
  2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN CFFI-GROVEL:PROCESS-GROVEL-FILE) {805DFDFEB}>)
  3: (CFFI-GROVEL:PROCESS-GROVEL-FILE #P"/usr/home/wgl/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix.lisp" #P"/usr/home/wgl/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wgl/..
  4: ((:METHOD ASDF/ACTION:PERFORM (CFFI-GROVEL::PROCESS-OP CFFI-GROVEL:GROVEL-FILE)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "iolib/syscalls" "ffi-types">) [fast-method]
  5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "iolib/syscalls" "ffi-types">)
  6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
  7: ((:METHOD ASDF/ACTION:PERFORM :AROUND (CFFI-GROVEL::PROCESS-OP CFFI-GROVEL::CC-FLAGS-MIXIN)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "iolib/syscalls" "ffi-types">) [fast-method]
  8: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "iolib/syscalls" "ffi-types">) [fast-method]
  9: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1004F7FAB3}>) [fast-method]
 10: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 11: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1004F7FAB3}>) [fast-method]
 12: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "rescancam"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
 13: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "rescancam">)
 14: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 15: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "rescancam">) [fast-method]
 16: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "rescancam")
 17: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 18: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "rescancam") [fast-method]
 19: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10054B1C9B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
 --more--

**Comment by wglb** [comment]
This seems to be failing on freebsd 13 only.

**Comment by luismbo** [comment]
Can you load it using plain ASDF or use Quicklisp's verbose mode to see why cc is failing?

**Comment by phoe** [comment]
Or just turn the list of strings from your error into a command and run it. Try running this to see the CC error:

```
cc -o /usr/home/wgl/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wgl/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel-tmpZ7CBRM0G.o -c -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -fno-omit-frame-pointer -fPIC -I/usr/home/wgl/quicklisp/dists/quicklisp/software/cffi-20230214-git/ /usr/home/wgl/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wgl/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel.c
```

**Comment by wglb** [comment]
Here is the command from the sbcl compile output:
cc -o /usr/home/wglb/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wglb/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel-tmp10401X32.o -c -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -fno-omit-frame-pointer -fPIC -I/usr/home/wglb/quicklisp/dists/quicklisp/software/cffi-20230214-git/ /usr/home/wglb/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wglb/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel.c

and the result is when pasted into a shell is

/usr/home/wglb/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wglb/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel.c:6:10: fatal error: 'lfp.h' file not found
#include <lfp.h>
         ^~~~~~~

**Comment by phoe** [comment]
> fatal error: 'lfp.h' file not found
> #include <lfp.h>

As per the manual in https://github.com/sionescu/iolib, please install https://github.com/sionescu/libfixposix which provides `lfp.h`.

**Comment by wglb** [comment]
Lpf has already been installed and is at /usr/local/include/lfp.h.

**Comment by wglb** [comment]
If I modify the above compile command to be 

cc -I/usr/local/include -o /usr/home/wglb/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wglb/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel-tmpUX5S4ADN.o -c -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -fno-omit-frame-pointer -fPIC -I/usr/home/wglb/quicklisp/dists/quicklisp/software/cffi-20230214-git/ /usr/home/wglb/.cache/common-lisp/sbcl-2.3.3-bsd-x64/usr/home/wglb/quicklisp/dists/quicklisp/software/iolib-v0.8.4/src/syscalls/ffi-types-unix__grovel.c

It compiles, but with warnings.

**Comment by sionescu** [comment]
What Linux distribution is this ? It would be very unusual for /usr/local/include not to be included in the default include list.

**Comment by wglb** [comment]
As shown in the compile line, this is FreeBSD (13)

**Comment by wglb** [comment]
I apologize for not mentioning that from the beginning.

**Comment by wglb** [comment]
I've worked around this by adding C_INCLUDE_PATH in my .bashrc, and all works well.  Perhaps this is the permanent solution?

**Comment by sionescu** [comment]
Probably yes: setting C_INCLUDE_PATH and LIBRARY_PATH. CFFI simply expects the native C toolchain to work.

**Comment by luismbo** [comment]
Marking as closed, then. @sionescu, @phoe  thanks for your help sorting this out.
