### ISSUE TITLE
How to use a specific C++ compiler?

### ISSUE THREAD

**Issue by adamryczkowski** [cffi/cffi#359]
We have an existing large C++ project which we build using a wide range of compilers and their versions (msvc, gcc, clang).

I would like to add a Python wrapper around the unit tests of the project, preferably using the CFFI Python library.

I need to ensure that the CFFI uses the same compiler as the project itself. Is there a way to initialize the CFFI with a path to our C++ compiler?

I've asked the question on https://stackoverflow.com/q/75896430/1261153 a month ago, but got no response.

**Comment by sionescu** [comment]
This is not the Python project named CFFI.
