### ISSUE TITLE
Support for SIMD

### ISSUE THREAD

**Issue by digikar99** [cffi/cffi#360]
Is there a way to use CFFI with SIMD instructions? If not, what would be the roadblocks to get this working?

**Comment by sionescu** [comment]
What do you mean by that ? CFFI has nothing to do with instruction sets.

**Comment by digikar99** [comment]
Ah, right. What I wanted to mean was: CFFI allows for specifying that the argument or return value of a function is a `float` or a `double` or a `char`. Likewise, is there a way to specify that the argument or the return value of a function is a 128 bit or 256 bit SIMD pack?

**Comment by luismbo** [comment]
@digikar99 the usual way would be for a Lisp implementation to offer support for simd types, which CFFI could then use.

Alternatively, we could do it via libffi. There are some discussions there about such support but it seems to be a work in progress. I couldn't quite tell what the current status is.

Finally, you could write a wrapper library that converts simd types into something that CFFI can work with. cffi-grovel could help with that: https://cffi.common-lisp.dev/manual/html_node/Wrapper-for-Inline_002fStatic-Functions-and-Macros.html

**Comment by digikar99** [comment]
I see, thank you, that helps! So at least one good way would be to work with marcoheisig to help with bringing the SIMD types to other implementations.

**Comment by luismbo** [comment]
AFAIK, SBCL's FFI does not support SIMD types.

**Comment by bohonghuang** [comment]
> AFAIK, SBCL's FFI does not support SIMD types.

That's not entirely correct. It is possible to use SIMD instructions on foreign memory by deceiving SBCL about the variable type using `sb-ext:truly-the`.

**Comment by phoe** [comment]
I don't think "support" and "deceiving" go well in one sentence. Maybe 
it's *possible* with SBCL to do this, but by accident rather than by 
design and tests - I'd ask what happens e.g. in case of memory misalignment.

**Comment by bohonghuang** [comment]
> Maybe it's *possible* with SBCL to do this, but by accident rather than by design and tests

It is indeed not well supported, but at least it is not working by accident on the latest version of SBCL.

``` lisp
(cffi:defcstruct vector3
  (x :float)
  (y :float)
  (z :float))

(cffi:defcstruct matrix3
  (v1 (:struct vector3))
  (v2 (:struct vector3))
  (v3 (:struct vector3)))

(defun test-simd ()
  (cffi:with-foreign-object (pointer '(:struct matrix3))
    (let ((v1 (cffi:foreign-slot-pointer pointer '(:struct matrix3) 'v1))
          (v2 (cffi:foreign-slot-pointer pointer '(:struct matrix3) 'v2))
          (v3 (cffi:foreign-slot-pointer pointer '(:struct matrix3) 'v3)))
      (cffi:with-foreign-slots ((x y z) v1 (:struct vector3))
        (setf x 1s0 y 2s0 z 3s0))
      (cffi:with-foreign-slots ((x y z) v2 (:struct vector3))
        (setf x 4s0 y 5s0 z 6s0))
      (cffi:with-foreign-slots ((x y z) v3 (:struct vector3))
        (setf x 7s0 y 8s0 z 9s0)))
    (let ((vec (sb-ext:truly-the sb-simd-avx:f32vec (sb-kernel:%make-lisp-obj (1- (cffi:pointer-address pointer))))))
      (sb-simd-avx:f32.8-horizontal+
       (sb-simd-avx:f32.8+
        (sb-simd-avx:f32.8-aref vec 0)
        (sb-simd-avx:f32.8-aref vec 1))))))

(test-simd) ; => 80.0
```
