### ISSUE TITLE
Feature Request (bug?) easy: Allow #define replace for function modifiers (common use case: "#define INLINE ")

### ISSUE THREAD

**Issue by CGDogan** [cffi/cffi#367]
## Feature summary:

Please help make:

```h
#define INLINE

INLINE my_func1(void);
INLINE my_func2(void);
```

not fail.

Currently:

```
cffi.CDefError: cannot parse "INLINE my_func(void);"
<cdef source string>:19:20: before: my_func
```

## My usecase

My `lib.h` was:

```c
#ifndef MYLIB
#define MYLIB

#ifdef GNUBLABLA
#define MYINLINE inline
#else
#define MYINLINE
#endif

MYINLINE my_func(void);

#endif
```

So I split it into three for cffi:

```
├── mylib____inner.h
├── mylib.h
└── mylib_cffi.h
```

where:

`mylib____inner.h`:
```h
MYINLINE my_func(void);
```

`mylib.h`:
```h
#ifndef MYLIB
#define MYLIB

#ifdef GNUBLABLA
#define MYINLINE inline
#else
#define MYINLINE
#endif

#include "mylib____inner.h"

#endif
```

`mylib_cffi.h`:
```h
#define MYINLINE

// Then here I concat using Python `mylib____inner.h`
```

I think this would be useful for many people, what do you think?

**Comment by CGDogan** [comment]
Oh no sorry

cffi.CDefError: only supports one of the following syntax:
  #define JNI_EINVsssAL ...     (literally dot-dot-dot)
  #define JNI_EINVsssAL NUMBER  (with NUMBER an integer constant, decimal/hex/octal)

**Comment by luismbo** [comment]
wrong project, the python project lives elsewhere
