### ISSUE TITLE
*foreign-library-directories*

### ISSUE THREAD

**Issue by omarbassam88** [cffi/cffi#378]
Why is the *foreign-library-directories*  is set only to look for `LD_LIBRARY_PATH` on darwin and not on Linux?
I would like to be able to use environment variables to pass the path to libraries without having to modify the variable everytime.

https://github.com/cffi/cffi/blob/6b746314eaa49fbcdbb5e73bba38aa9b659c6f32/src/libraries.lisp#L68

**Comment by omarbassam88** [comment]
Suggestion:

```lisp
(defvar *foreign-library-directories*
  (if (or (featurep :unix) (featurep :darwin))
      '((explode-path-environment-variable "LD_LIBRARY_PATH")
        (explode-path-environment-variable "DYLD_LIBRARY_PATH")
        (uiop:getcwd)
        (darwin-fallback-library-path))
      '())
  "List onto which user-defined library paths can be pushed.")
```

**Comment by omarbassam88** [comment]
OR:

```lisp
(defvar *foreign-library-directories*
  `((explode-path-environment-variable "LD_LIBRARY_PATH")
    (explode-path-environment-variable "DYLD_LIBRARY_PATH")
    (uiop:getcwd)
    ,(when (featurep :darwin) '(darwin-fallback-library-path)))
  "List onto which user-defined library paths can be pushed.")
```

**Comment by luismbo** [comment]
https://bugs.launchpad.net/cffi/+bug/1414277 explains the motivation. I forget the details, but on OS X, perhaps for certain types of executables, `dlopen()` doesn't do any searching in the regular places. It's a bit of a hack because it won't solve the issue for library dependencies and it's possibly a security issue.

On Linux, `dlopen()` does take `LD_LIBRARY_PATH` into account, doesn't it?

**Comment by omarbassam88** [comment]
> On Linux, dlopen() does take LD_LIBRARY_PATH into account, doesn't it?

apparently it doesn't. Because I'm using `nix`, the libraries are not in the default location under `/usr/lib` directory. 
I'm actually not using `cffi` directly. But because packages such as `clack` and `woo` use it internally, I had to do this modification in order for them to work.

The above code examples that I've given worked for me.
Happy to make a PR if it's OK with you.

**Comment by luismbo** [comment]
I'm not familiar with the details of how `nix` works, but I think you should look into how to get a useful shared library environment in nix. Quick googling turned up this: https://unix.stackexchange.com/questions/190719/how-to-use-libraries-installed-by-nix-at-run-time maybe it helps?

**Comment by omarbassam88** [comment]
This is exactly what I am trying to do. The link you mentioned uses `LD_LIBRARY_PATH` environment variable and point it to the path where nix installs its libraries.

**Comment by luismbo** [comment]
Are you setting `LD_LIBRARY_PATH` within the Lisp image or before launching your program?

**Comment by omarbassam88** [comment]
> Are you setting `LD_LIBRARY_PATH` within the Lisp image or before launching your program?

It is set outside the Lisp Image in my environment. I'm sure that the environment variable is set correctly because when I get it using `(uiop:getenv "LD_LIBRARY_PATH")` it gives me the correct path where the libraries are installed. The issue is in the `*foreign-library-directories*` as I explained before.

**Comment by luismbo** [comment]
Do you have any clue why `dlopen()` is ignoring the environment variable?

**Comment by omarbassam88** [comment]
According to the dlopen manual:
> If, at the time that the program was started, the environment variable LD_LIBRARY_PATH was defined to contain a colon-         separated list of directories, then these are searched.  (As a security measure, this variable is ignored for set-user-ID and set-group-ID programs.)

https://man7.org/linux/man-pages/man3/dlopen.3.html

**Comment by omarbassam88** [comment]
Here's a simple [PR](https://github.com/cffi/cffi/pull/380) as a suggestion to fix the issue. @luismbo

**Comment by luismbo** [comment]
As I've tried to explain, I think this is a bit of a hack. Since we don't have a better solution yet, I'd be willing to accept it if it's not turned on by default. Perhaps the behaviour can be activated in response to `*features*` and you could add that to your init file. Would that work for you?

**Comment by omarbassam88** [comment]
Which init file do you mean? Can you give an example of how to be activated in response to `*features*`? Isn't this what `featurep` does?

**Comment by russell** [comment]
in guix (which is similar to nix), i was able to get linking to work if i setup my profile to included all the libraries i depended on and then set the LD_LIBRARY_PATH to point at the directory.  Everything in that directory is a symlink to a file in the store somewhere, and SBCL can load libraries from it.

**Comment by omarbassam88** [comment]
> in guix (which is similar to nix), i was able to get linking to work if i setup my profile to included all the libraries i depended on and then set the LD_LIBRARY_PATH to point at the directory. Everything in that directory is a symlink to a file in the store somewhere, and SBCL can load libraries from it.

Do you mean that you set your LD_LIBRARY_PATH to the absolute path and not the path to the symlink?

**Comment by omarbassam88** [comment]
I finally managed to solve this issue. I'll post what I did here in case someone else is facing the same issue.
The reason this issue was happening was that I was setting `LD_LIBRARY_PATH` to `~/.nix-profile/lib` which is a symlink. Apparently `LD_LIBRARY_PATH` works only with absolute paths.
So, This can be solved by different methods: 

1. Setting `LD_LIBRARY_PATH` in your .profile or .bashrc or .zshrc as follows:
```sh
export LD_LIBRARY_PATH=$(readlink ~/.nix-profile/lib):$LD_LIBRARY_PATH
```
2. Using `home.sessionVariables` in your home-manager configuration as follows:
```nix
home.sessionVariables =  {
  LD_LIBRARY_PATH = lib.concatStringsSep ":" [
      (lib.makeLibraryPath (with pkgs; [
       # the list of libraries you want to be added to your path
        openssl
        libev
        sqlite
        ncurses
      ]))
      "$LD_LIBRARY_PATH"
      ];
};

```

If you use any of those solutions you won't need to add anything to your .sbclrc and you won't need to modify the `cffi:*foreign-library-directories*`.

I hope this is helpful for anyone in the future who might face the same issue.

**Comment by luismbo** [comment]
Thanks Omar. Do you think this is something that should be added to Nix's documentation? Perhaps they have ideas on how to simplify the setup.

**Comment by omarbassam88** [comment]
I'm not sure at this point whether it's a nix thing or a `dlopen` thing. But I believe this is going to be a common issue for any one using Common Lisp on Nix.
